Repository Log-Road/Road-FrontEnd, pull requests merged in 2024-03, with the labels that each got.

#3 (#2) styles 폴더 생성, 디자인 시스템 추가
  fonts.d.ts
  package-lock.json
  package.json
  src/fonts/Pretendard-Medium.ttf
  src/fonts/Pretendard-Regular.ttf
  src/fonts/Pretendard-SemiBold.ttf
  src/index.js
  src/styles/GlobalStyle.ts
  src/styles/colors.ts
Labels: 기능 구현

#5 Feature/#4 ranking page
  custom.d.ts
  package-lock.json
  package.json
  public/index.html
  src/Router/Router.jsx
  src/assets/Profile.svg
  src/assets/ProjectImg.svg
  src/assets/index.js
  src/components/Header.tsx
  src/components/List.tsx
  src/components/ProjectBox.tsx
  src/components/index.js
  src/fonts/ABeeZee-Regular.ttf
  src/index.js
  src/pages/RankingPage.tsx
  src/pages/index.js
  src/styles/GlobalStyle.ts
  tsconfig.json
Labels: 퍼블리싱

#9 메인페이지 퍼블리싱
  src/Router/Router.jsx
  src/assets/Filter.svg
  src/assets/Search.svg
  src/components/MainHeader.tsx
  src/components/MainProject.tsx
  src/pages/Main.tsx
Labels: 퍼블리싱

#12 (#11) 헤더 수정 및 검색바 기능 추가
  package-lock.json
  package.json
  src/assets/Cancel.svg
  src/components/Header.tsx
  src/components/MainHeader.tsx
  src/pages/Main.tsx
Labels: 기능 구현, 퍼블리싱

#14 (#11) 헤더 검색바 수정
  public/index.html
  src/Router/Router.jsx
  src/components/Header.tsx
Labels: 기능 구현

#19 (#13) 폰트 수정
  src/components/Header.tsx
  src/fonts/ABeeZee-Regular.ttf
  src/pages/RankingPage.tsx
  src/styles/GlobalStyle.ts
Labels: 버그

#24 (#23) 아이디 찾기 페이지 퍼블리싱
  src/Router/Router.jsx
  src/pages/FindID.tsx
Labels: 퍼블리싱

#26 (#23) 아이디 찾기 페이지 수정
  src/pages/FindID.tsx
Labels: 퍼블리싱

#27 (#23) 아이디 찾기 페이지 수정
  src/pages/FindID.tsx
Labels: 퍼블리싱

#32 메인페이지 코드 refactoring
  src/pages/Main.tsx
Labels: 리팩토링

#33 (#25) 비밀번호 찾기 페이지 오류 수정
  src/pages/FindPassWord.tsx
Labels: 버그

#37 (#21) 어드민 인원 정보 페이지 퍼블리싱
  src/Router/Router.jsx
  src/assets/DownArrow.svg
  src/assets/UpArrow.svg
  src/assets/Upload.svg
  src/components/Modal/ApproveUpload.tsx
  src/components/Modal/CancelApprove.tsx
  src/components/Modal/RefusalUpload.tsx
  src/pages/Admin/InformationPersonnel.tsx
  src/pages/Admin/StudentInfoEdit.tsx
Labels: 퍼블리싱
